services:
  loc:
    image: nsulliv7/ser516-loc:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  code-comment:
    image: mkapure/app-code-comment-coverage-backend:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  fogindex:
    image: mkapure/fogindex:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  defects-stats:
    image: mkapure/defects-stats:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  defects-triage:
    image: mkapure/app-defects-triage:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  mttr:
    image: nsulliv7/ser516-mttr:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  cc:
    image: nsulliv7/ser516-cc:${VERSION:-latest}
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  defects-over-time:
    image: nsulliv7/ser516-defects-over-time:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  cyclo:
    image: nsulliv7/ser516-cyclo:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  hal:
    image: nsulliv7/ser516-hal:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  ici:
    image: nsulliv7/ser516-ici:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always
  lcomhs:
    image: gopu007/app-lcomhs:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always
  lcom4:
    image: gopu007/app-lcom4:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always
  efferent-coupling:
    image: gopu007/app-efferent-coupling:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always
  afferent-coupling:
    image: gopu007/app-afferent-coupling:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always
  fan-in:
    image: mkapure/app-fan-in-service:${VERSION:-latest}
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always 
  store_metrics:
    image: spraka52/ser516-store-metrics:${VERSION:-latest}
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    depends_on:
      - mongo
    restart: always

  middleware:
    image: spraka52/ser516-middleware:${VERSION:-latest}
    ports:
      - "${GATEWAY_PORT}:5000"
    environment:
      - SERVICES=cc,loc,mttr,defects-over-time,cyclo,hal,ici,code-comment,lcomhs,lcom4,efferent-coupling,afferent-coupling,fogindex,defects-stats,defects-triage,fan-in
      - MONGO_URI=mongodb://mongo:27017
      - STORE_METRICS_URL=http://store_metrics:5000/store_metrics
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    depends_on:
      - loc
      - cc
      - cyclo
      - hal
      - ici
      - mttr
      - defects-over-time
      - lcomhs
      - lcom4
      - efferent-coupling
      - afferent-coupling
      - fan-in
      - store_metrics
      - code-comment
      - defects-stats
      - defects-triage
      - fogindex
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - analysis-network

  client:
    image: gopu007/app-frontend:${VERSION:-latest}
    ports:
      - "${CLIENT_PORT}:5173"
    restart: always

networks:
  analysis-network:
    name: analysis-network
    driver: bridge

volumes:
  shared-repos:
