services:
  loc:
    image: nsulliv7/ser516-loc:v0.4.4
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  fogindex:
    image: mkapure/fogindex:v7.0.0
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  defects-stats:
    image: mkapure/defects-stats:v6.0.0
    volumes:
      - shared-repos:/shared/repos
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - analysis-network
    restart: always

  mttr:
    image: nsulliv7/ser516-mttr:v0.4.4
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  cc:
    image: nsulliv7/ser516-cc:v0.4.4
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    restart: always

  defects-over-time:
    image: nsulliv7/ser516-defects-over-time:v0.4.4
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  cyclo:
    image: nsulliv7/ser516-cyclo:v0.4.4
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  hal:
    image: nsulliv7/ser516-hal:v0.4.4
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  ici:
    image: nsulliv7/ser516-ici:v0.4.4
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  lcomhs:
    image: gopu007/app-lcomhs:v.0.0.1
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  lcom4:
    image: gopu007/app-lcom4:v.0.0.1
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
    restart: always

  store_metrics:
    image: spraka52/ser516-store-metrics:v0.0.8
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    depends_on:
      - mongo
    restart: always

  middleware:
    image: spraka52/ser516-middleware:v0.0.7
    ports:
      - "${GATEWAY_PORT}:5000"
    environment:
      - SERVICES=cc,loc,mttr,defects-over-time,cyclo,ici,lcomhs,lcom4,fogindex,defects-stats
      - MONGO_URI=mongodb://mongo:27017
      - STORE_METRICS_URL=http://store_metrics:5000/store_metrics
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network
    depends_on:
      - loc
      - cc
      - cyclo
      - hal
      - ici
      - mttr
      - defects-over-time
      - lcomhs
      - lcom4
      - store_metrics
      - fogindex
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - analysis-network

  client:
    image: gopu007/app-frontend:v0.0.1
    ports:
      - "${CLIENT_PORT}:5173"
    restart: always

networks:
  analysis-network:
    name: analysis-network
    driver: bridge

volumes:
  shared-repos:
